/* WORK IN PROGRESS */

CREATE TABLE IF NOT EXISTS videos (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	file VARCHAR(2048) NOT NULL UNIQUE,
	duration BIGINT NOT NULL,
	size BIGINT NOT NULL,
	width INT NOT NULL,
	height INT NOT NULL,
	framerate FLOAT NOT NULL,
	extractedAudioFile VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS audios (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	file VARCHAR(2048) NOT NULL UNIQUE,
	duration BIGINT NOT NULL,
	size BIGINT NOT NULL,
	bitrate INT NOT NULL
);

CREATE TABLE IF NOT EXISTS images (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	file VARCHAR(2048) NOT NULL UNIQUE,
	size BIGINT NOT NULL,
	width INT NOT NULL,
	height INT NOT NULL
);