/* WORK IN PROGRESS */

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) UNIQUE NOT NULL,
	password CHARACTER(256) NOT NULL,
	groupid INTEGER,
	FOREIGN KEY(groupid) REFERENCES groups(id)
);

CREATE TABLE IF NOT EXISTS groups (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(256) UNIQUE NOT NULL,
	permissions VARCHAR(2048)
);